swagger: "2.0"
info:
  title: "お菓子"
  description: "お菓子を返すAPI"
  version: 1.0.0
basePath: "/api"
tags:
  - name: "item"
    description: "商品"
host: localhost:8080
paths:
  /items/{item_id}:
    get:
      tags:
        - "item"
      summary: "商品の詳細を返す"
      produces:
        - "application/json"
      parameters:
        - in: "path"
          name: "item_id"
          type: "integer"
          required: true
      responses:
        200:
          description: "リクエストが成功した場合"
          schema:
            $ref: "#/definitions/Item"
        404:
          description: "指定された商品が見つからない場合"
definitions:
  Item:
    description: "商品の詳細情報"
    type: object
    properties:
      name:
        type: "string"
      description:
        type: "string"
      category:
        type: "string"
      price:
        type: "integer"
        description: "金額"
    example:
      name: "ブラックサンダー"
      description: |-
        みんな大好きブラックサンダーが装い改め新登場！
        1994年の発売から20年以上愛されている「ブラックサンダー」が2003年のパッケージ変更から14年ぶりにフルリニューアル！
        チョコレートとビスケットのバランスを見直し、カバーチョコレートを増量！
      category: "チョコレート"
      price: 30
